import smtplib
import os
from email.message import EmailMessage

sender_email = os.getenv("EMAIL_FROM")
receiver_email = os.getenv("EMAIL_TO")
email_password = os.getenv("EMAIL_PASSWORD")

msg = EmailMessage()
msg["Subject"] = "Least performing 2 stores"
msg["From"] = sender_email
msg["To"] = receiver_email
msg.set_content("Hello,\n\nI hope this mail finds you\nPlease find the attached CSV file generated by the pipeline.\n\nRegards,\nTharun Azure Devops")

csv_file_path = "lowest_performing_store.csv"
with open(csv_file_path, "rb") as f:
    msg.add_attachment(f.read(), maintype="text", subtype="csv", filename="lowest_performing_store.csv")

try:
    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.starttls()
        smtp.login(sender_email, email_password)
        smtp.send_message(msg)
        print("least prerforming stores report successfully sent with attachments.")
except Exception as e:
    print(f"Failed to send email: {e}")
